=== mickeywstahl/MDDT/data-types/x73-idl-rti-dds/src/main/resources/resource/app/app_support/rtiddsgen/schema/rtiddsgen_configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
(c) Copyright, Real-Time Innovations, Inc. 2022.  All rights reserved.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="configuration">
    <xsd:complexType>
      <xsd:sequence>
        <!-- Command line options -->
        <xsd:element name="command_line_options">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="command_line_option" maxOccurs="unbounded" minOccurs="0">
                <xsd:complexType>
                  <xsd:all>
                    <xsd:element type="xsd:string" name="name" maxOccurs="1" minOccurs="1"/>
                    <xsd:element type="xsd:string" name="help_msg" maxOccurs="1" minOccurs="1"/>
                    <xsd:element type="xsd:boolean" name="supported" maxOccurs="1" minOccurs="1"/>
                    <xsd:element type="xsd:boolean" name="hidden" maxOccurs="1" minOccurs="1"/>
                    <!-- The following elements are optional -->
                    <xsd:element type="xsd:boolean" name="deprecated" maxOccurs="1" minOccurs="0"/>
                    <xsd:element type="xsd:string" name="param" maxOccurs="1" minOccurs="0"/>
                    <xsd:element type="xsd:boolean" name="telemetry" maxOccurs="1" minOccurs="0"/>
                    <xsd:element type="xsd:string" name="short_name" maxOccurs="1" minOccurs="0"/>
                  </xsd:all>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <!-- Annotations -->
        <xsd:element name="annotations">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="annotation" maxOccurs="unbounded" minOccurs="0">
                <xsd:complexType>
                  <xsd:all>
                    <xsd:element type="xsd:string" name="name" maxOccurs="1" minOccurs="1"/>
                    <xsd:element type="annotation_status_type" name="status" maxOccurs="1" minOccurs="1"/>
                    <!-- The following element is optional -->
                    <xsd:element type="xsd:string" name="custom_warning_msg" maxOccurs="1" minOccurs="0"/>
                  </xsd:all>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <!-- Possible values status element can get -->
  <xsd:simpleType name="annotation_status_type">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Supported"/>
      <xsd:enumeration value="Warning"/>
      <xsd:enumeration value="Error"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== mickeywstahl/MDDT/data-types/x73-idl-rti-dds/src/main/resources/resource/app/app_support/rtiddsgen/configuration/rtiddsgen_configuration.xml
<?xml version="1.0"?>

<!--
(c) Copyright, Real-Time Innovations, Inc. 2022.  All rights reserved.
-->

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../schema/rtiddsgen_configuration.xsd">
<command_line_options>
    <command_line_option>
        <name>help</name>
        <help_msg>
        Prints this message.
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
    </command_line_option>
    <command_line_option>
        <name>showTemplates</name>
        <help_msg>
        Prints and generates an xml file both containing a list
        of the available example templates, organized per language, that can
        be used with Code Generator -exampleTemplate option.
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
    </command_line_option>
    <command_line_option>
        <name>allocateWithMalloc</name>
        <help_msg>
        Use this flag to get backwards compatibility
        when allocating optional members with DDS_Heap_malloc in C++ (CODEGENII-620).
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
        <short_name>awm</short_name>
    </command_line_option>
    <command_line_option>
        <name>autoGenFiles</name>
        <param>&lt;arch&gt;</param>
        <help_msg>
        Updates the autogenerated files, i.e, typefiles and makefile/project files
        shortcut for: -update &lt;typefiles&gt; -update &lt;makefiles&gt; -platform &lt;arch&gt;"
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
        <short_name>agf</short_name>
    </command_line_option>
    <command_line_option>
        <name>create</name>
        <param>&lt;typefiles, examplefiles, makefiles&gt;</param>
        <help_msg>
        Creates the files
        indicated if they do not exist. For example:
        rtiddsgen -language C++11 -create typefiles test.idl
        If the files already exist, the files are not modified and a
        warning is printed. There can be multiple -create options.
        If you specify both -create and -update for the same file type,
        only the -update will be applied. If you use -create makefiles,
        the -platform &lt;arch&gt; option is required. For example:
        rtiddsgen -language c -create makefiles -platform x64Darwin20clang12.0 test.idl
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
    </command_line_option>
    <command_line_option>
        <name>convertToIdl</name>
        <help_msg>
        Converts the input file into an equivalent IDL file.
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
        <short_name>cti</short_name>
    </command_line_option>
    <command_line_option>
        <name>convertToXml</name>
        <help_msg>
        Converts the input file into an equivalent XML file.
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
        <short_name>ctxml</short_name>
    </command_line_option>
    <command_line_option>
        <name>convertToXsd</name>
        <help_msg>
        Converts the input file into an equivalent XSD file.
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
        <short_name>ctxsd</short_name>
    </command_line_option>
    <command_line_option>
        <name>xmlTypeLibrary</name>
        <help_msg>
        When generating XML use the type_library format instead of the types format
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
    </command_line_option>
    <command_line_option>
        <name>D</name>
        <param>&lt;name&gt;[=&lt;value&gt;]</param>
        <help_msg>Defines preprocessor macros</help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
    </command_line_option>
    <command_line_option>
        <name>d</name>
        <param>&lt;outdir&gt;</param>
        <help_msg>
        Generate output in the specified directory
        (default: IDL input file's directory)
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
    </command_line_option>
    <command_line_option>
        <name>use52CKeyhash</name>
        <help_msg>
        This flag is ignored
        </help_msg>
        <supported>true</supported>
        <hidden>true</hidden>
        <deprecated>true</deprecated>
    </command_line_option>
    <command_line_option>
        <name>use52JavaKeyhash</name>
        <help_msg>
        This option should be used when compatibility
        with 5.2.3 and earlier GARs is required when using keyed mutable
        types. Deprecate, use -use52Keyhash
        </help_msg>
        <supported>true</supported>
        <hidden>true</hidden>
        <deprecated>true</deprecated>
    </command_line_option>
    <command_line_option>
        <name>use52Keyhash</name>
        <help_msg>
        This option should be used when compatibility
        with 5.2.3 and earlier GARs is required when using keyed mutable
        types (CODEGENII-501 and CODEGENII-693)
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
    </command_line_option>
    <command_line_option>
        <name>use526Keyhash</name>
        <help_msg>
        This option should be used when compatibility
        with 5.2.6 is required when using keyed mutable types (CODEGENII-693)
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
    </command_line_option>
    <command_line_option>
        <name>dllExportMacroSuffix</name>
        <param>&lt;suffix&gt;</param>
        <help_msg>
        Defines the suffix of the macro that is
        used to export symbols when building Windows DLLs.
        The default macro is NDDS_USER_DLL_EXPORT. When this option is
        specified, the name of the macro is NDDS_USER_DLL_EXPORT_&lt;Suffix&gt;
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
    </command_line_option>
    <command_line_option>
        <name>enableEscapeChar</name>
        <help_msg>
        Enables the usage of the escape character '_' in IDL
        identifiers.
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
    </command_line_option>
    <command_line_option>
        <name>example</name>
        <param>&lt;arch&gt;</param>
        <help_msg>
        Generates type files, example files and makefile
        shortcut for: -create &lt;typefiles&gt; -create &lt;examplefiles&gt;
                      -create &lt;makefiles&gt; -platform &lt;arch&gt;
        Valid &lt;arch&gt; arguments are:
        For all languages but C#:
          universal (Generate compatible publisher/subscriber code for all
          supported platforms. It won't generate makefiles/project files)
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
    </command_line_option>
    <command_line_option>
        <name>exampleTemplate</name>
        <param>&lt;templateName&gt;</param>
        <help_msg>
        Generate an example application using
        custom publisher and subscriber templates. You can also optionally
        add a QoS template. These templates should be saved under:
          $NDDSHOME/resource/app/app_support/rtiddsgen/templates/example/&lt;language&gt;/&lt;templateName>&gt;
        This option is not supported in Ada.
        In order to use this option, you have to use one of the next ones:
          -create examplefiles
          -update examplefiles
          -example &lt;architecture&gt;
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
        <short_name>et</short_name>
    </command_line_option>
    <command_line_option>
        <name>express</name>
        <help_msg>
        This flag is ignored
        </help_msg>
        <supported>true</supported>
        <hidden>true</hidden>
        <deprecated>true</deprecated>
    </command_line_option>
    <command_line_option>
        <name>generateCTypeCode</name>
        <help_msg>
        This flag is ignored
        </help_msg>
        <supported>true</supported>
        <hidden>true</hidden>
        <deprecated>true</deprecated>
    </command_line_option>
    <command_line_option>
        <name>I</name>
        <param>&lt;directory&gt;</param>
        <help_msg>
        Adds the directory to the list of directories to be searched
        for header files
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
    </command_line_option>
    <command_line_option>
        <name>inputIdl</name>
        <param>&lt;IDLInputFile.idl&gt;</param>
        <help_msg>
        Indicates that the input file is an IDL file
        independently of the file extension
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
        <telemetry>true</telemetry>
        <short_name>inIdl</short_name>
    </command_line_option>
    <command_line_option>
        <name>inputXml</name>
        <param>&lt;XMLInputFile.xml&gt;</param>
        <help_msg>
        Indicates that the input file is an XML file
        independently of the file extension
        </help_msg>
        <supported>true</supported>
        <hidden>false</hidden>
